### ISSUE TITLE
0.2.0 Checklist

### ISSUE THREAD

**Issue by Anders429** [Anders429/more_ranges#3]
This is the checklist of things that need to happen before the `0.2.0` release.

- [x] Implement [`Iterator`](https://doc.rust-lang.org/std/iter/trait.Iterator.html).
- [x] Implement [`DoubleEndedIterator`](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html).
- [x] Implement [`FusedIterator`](https://doc.rust-lang.org/std/iter/trait.FusedIterator.html).
- [x] Implement [`ExactSizeIterator`](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html). These must be dependent on the target's pointer width.
- [ ] Implement [`TrustedLen`](https://doc.rust-lang.org/std/iter/trait.TrustedLen.html).
- [x] Implement [`Index`](https://doc.rust-lang.org/std/ops/trait.Index.html) for `[T]`, `Vec<T>`, `&str`, and `String`. Also implement `Index` for `CStr` using `RangeFromExclusive`.
- [x] Implement [`Serialize`](https://docs.serde.rs/serde/trait.Serialize.html) and
[`Deserialize`](https://docs.serde.rs/serde/trait.Deserialize.html) from [`serde`](https://crates.io/crates/serde).
- [ ] [`autocfg`](https://crates.io/crates/autocfg) is working towards some form of `nightly` feature probing. This needs to be available to make the above features usable, since some of them require `nightly`, but we don't want to restrict the crate to nightly.
- [x] Set up documentation using [`doc_item`](https://crates.io/crates/doc_item) to make it more clear what the requirements are for certain parts of the crate.
- [ ] `rustdoc` issue with foreign implementations not being shown in documentation needs to be resolved (see #2). This only needs to be available in `nightly`, since that is what [docs.rs](https://docs.rs/) uses. We need this to be fixed before release, or else half of the documentation will be missing. There is a [PR](https://github.com/rust-lang/rust/pull/82496) to fix it, but it seems to be blocked currently.

**Comment by Anders429** [comment]
Put out a release with *most* of these features. Doesn't include `TrustedLen`, since it's a nightly feature that has had basically no traction. Doesn't include any `autocfg` build shenanigans because I've come to learn that trying to mess with that stuff is a nightmare. And doesn't include `doc_item` because there is no need for it now that I've squashed the scope creep.

In general, since I planned this release I've learned that trying to juggle and support a ton of nightly features and features that are dependent on your environment is a massive waste of time. I was glad to see that this release could come together in a much more straightforward fashion.
